services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: rate-limiter
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
